spring.application.name=KworiWebSite

server.port=${PORT:8080}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.servlet.context-path=/

# DATABASE CONFIG
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/kworiDb?currentSchema=public}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:esselAnthony123$$}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.use_sql_comments=false
spring.jpa.properties.hibernate.default_schema=public
spring.jpa.properties.hibernate.hbm2ddl.halt_on_error=true
spring.jpa.properties.hibernate.globally_quoted_identifiers=false
spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# FLYWAY
spring.flyway.enabled=false

# JWT CONFIGURATION
jwt.secret=${JWT_SECRET:T3mHWZSvweThAIQNquwbRi8WZmNjCOsn8lrX+nG32yA=}
jwt.access-expiration-ms=${JWT_ACCESS_EXPIRATION_MS:86400000}
jwt.refresh-expiration-ms=${JWT_REFRESH_EXPIRATION_MS:604800000}

# Token Encryption
security.token.encryption-key=${TOKEN_ENCRYPTION_KEY:aTa+si1HtVE5gRBP8qvAjOifhm/uQbOJ/1uDx22zC7Y=}

# HIKARI CONNECTION POOL
spring.datasource.hikari.connection-init-sql=SET search_path TO public
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.initialization-fail-timeout=0

# ASYNC THREAD POOL
spring.task.execution.pool.core-size=5
spring.task.execution.pool.max-size=10
spring.task.execution.pool.queue-capacity=25

# WEBSOCKET CONFIG
spring.websocket.max-text-message-size=65536
spring.websocket.max-binary-message-size=65536

# FILE UPLOAD CONFIG
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=50MB


# CLOUDINARY
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:dxxgd7p3i}
cloudinary.api-key=${CLOUDINARY_API_KEY:873262633583533}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:5QkeRBU-ECkCaxkDcpZ2gpvsYxs}

spring.jackson.deserialization.fail-on-unknown-properties=false